//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homologacion
    {
        public int IdHomologacion { get; set; }
        public int ID { get; set; }
        public int Programa { get; set; }
        public int IdAsignatura { get; set; }
        public int CodigoHomologacion { get; set; }
        public double NotaDefinitiva { get; set; }
        public int Idhomo { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual TipoHomologacion TipoHomologacion { get; set; }
        public virtual ProgramaEstudiantil ProgramaEstudiantil { get; set; }
        public virtual UsuarioAdmin UsuarioAdmin { get; set; }
    }
}
