//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioAdmin()
        {
            this.Homologacion = new HashSet<Homologacion>();
        }
    
        public int ID { get; set; }
        public int TipoDocumento { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Genero { get; set; }
        public string Correo { get; set; }
        public int Rol { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public int Programa { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual Genero Genero1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Homologacion> Homologacion { get; set; }
        public virtual ProgramaEstudiantil ProgramaEstudiantil { get; set; }
        public virtual Rol Rol1 { get; set; }
    }
}
